[colors]
background = '#2728228e'
black = '#272822'
blue = '#f92672'
cursor = '#f92672'
cyan = '#a6e22e'
foreground = '#f8f8f2'
green = '#f4bf75'
magenta = '#66d9ef'
red = '#ae81ff'
tabs = '#f8f8f2'
tabs-active = '#a1efe4'
white = '#f8f8f2'
yellow = '#f8f8f2'
dim-black = '#2728228e'
dim-blue = '#f926728e'
dim-cyan = '#a6e22e8e'
dim-foreground = '#f8f8f28e'
dim-green = '#f4bf758e'
dim-magenta = '#66d9ef8e'
dim-red = '#ae81ff8e'
dim-white = '#a1efe48e'
dim-yellow = '#f8f8f28e'
light-black = '#f92672'
light-blue = '#a6e22e'
light-cyan = '#f4bf75'
light-foreground = '#66d9ef'
light-green = '#ae81ff'
light-magenta = '#a1efe4'
light-red = '#f9f8f5'
light-white = '#f92672'
light-yellow = '#a6e22e'
